POST http://localhost:8000/api/v2/auth/user/login
Content-Type: application/json

{
    "email": "thuantd@funix.edu.vn",
    "password": "123456789"
}

###

POST http://localhost:8000/api/v2/auth/signup
Content-Type: application/json

{
    "email": "thuantd@funix.edu.vn",
    "password": "123",
    "username": "thuantd"
}

###


POST http://localhost:8000/api/v2/otp/verify-otp
Content-Type: application/json

{
    "email": "thuantd@funix.edu.vn",
    "otp": "328629"
}

###


POST http://localhost:8000/api/v2/otp/send-otp-again
Content-Type: application/json

{
    "email": "thuantd@funix.edu.vn"
}

###

GET http://localhost:8000/api/v2/product/get-item