POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "test1@gmail.com",
    "password": "123456789"
}

###

POST http://localhost:8000/api/v2/signup
Content-Type: application/json

{
    "email": "thuantd@funix.edu.vn",
    "password": "123456789",
    "username": "thuantd"
}

###


POST http://localhost:8000/api/v2/verify-otp
Content-Type: application/json

{
    "email": "thuantd@funix.edu.vn",
    "otp": "684418"
}

###


POST http://localhost:8000/api/v2/send-otp-again
Content-Type: application/json

{
    "email": "thuantd@funix.edu.vn"
}

###

GET http://localhost:8000/api/v2/get-item