@url=http://localhost:8000/v1/api/cart

PUT {{url}}
Content-Type: application/json
x-api-key: 3ba73ff48c21cd92f1f7fc1ce55e125f0bd176323da76c8abdfed7a79aeb56f6
x-client-id: 66e92fd3a4d6bdf2b3d0ebd7
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU5MmZkM2E0ZDZiZGYyYjNkMGViZDciLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwicGVybWl0Ijp7Il9pZCI6IjY2ZTkyZmQzYTRkNmJkZjJiM2QwZWJkYSIsInBlcm1pdF91c2VyIjpmYWxzZSwicGVybWl0X21vZGVyYXRvciI6ZmFsc2UsInBlcm1pdF9hZG1pbiI6dHJ1ZSwicGVybWl0X2d1ZXN0Ijp0cnVlLCJwZXJtaXRfc2hvcCI6ZmFsc2UsInBlcm1pdF91c2VySWQiOiI2NmU5MmZkM2E0ZDZiZGYyYjNkMGViZDciLCJjcmVhdGVkQXQiOiIyMDI0LTA5LTE3VDA3OjI5OjIzLjU3NVoiLCJ1cGRhdGVkQXQiOiIyMDI0LTA5LTE3VDA3OjI5OjIzLjU3NVoiLCJfX3YiOjB9LCJpYXQiOjE3MjY1NTgxODUsImV4cCI6MTcyNjczMDk4NX0.gdEsrSa7tWeKbTFg17yGY6H_PtjXRyaAF1vCwvl7q5M

{
    "item": "66e927588c2f81cf4c283c57",
    "quantity": -2
}

###
DELETE {{url}}/66e927588c2f81cf4c283c57
Content-Type: application/json
x-api-key: 3ba73ff48c21cd92f1f7fc1ce55e125f0bd176323da76c8abdfed7a79aeb56f6
x-client-id: 66e92fd3a4d6bdf2b3d0ebd7
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU5MmZkM2E0ZDZiZGYyYjNkMGViZDciLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwicGVybWl0Ijp7Il9pZCI6IjY2ZTkyZmQzYTRkNmJkZjJiM2QwZWJkYSIsInBlcm1pdF91c2VyIjpmYWxzZSwicGVybWl0X21vZGVyYXRvciI6ZmFsc2UsInBlcm1pdF9hZG1pbiI6dHJ1ZSwicGVybWl0X2d1ZXN0Ijp0cnVlLCJwZXJtaXRfc2hvcCI6ZmFsc2UsInBlcm1pdF91c2VySWQiOiI2NmU5MmZkM2E0ZDZiZGYyYjNkMGViZDciLCJjcmVhdGVkQXQiOiIyMDI0LTA5LTE3VDA3OjI5OjIzLjU3NVoiLCJ1cGRhdGVkQXQiOiIyMDI0LTA5LTE3VDA3OjI5OjIzLjU3NVoiLCJfX3YiOjB9LCJpYXQiOjE3MjY1NTgxODUsImV4cCI6MTcyNjczMDk4NX0.gdEsrSa7tWeKbTFg17yGY6H_PtjXRyaAF1vCwvl7q5M

