@url_dev=http://localhost:8000/v1/api/flashsale

POST {{url_dev}}
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67
x-client-id: 66caedd4533d3eefd8d16cc2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwicGVybWl0Ijp7InBlcm1pdF9zaG9wIjpmYWxzZSwiX2lkIjoiNjZjYWVkZDQ1MzNkM2VlZmQ4ZDE2Y2M0IiwicGVybWl0X3VzZXIiOnRydWUsInBlcm1pdF9tb2RlcmF0b3IiOmZhbHNlLCJwZXJtaXRfYWRtaW4iOnRydWUsInBlcm1pdF9ndWVzdCI6dHJ1ZSwicGVybWl0X3VzZXJJZCI6IjY2Y2FlZGQ0NTMzZDNlZWZkOGQxNmNjMiIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjVUMDg6Mzk6NDguNDAyWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDktMTRUMDc6NDc6NTQuMjM3WiIsIl9fdiI6MH0sImlhdCI6MTcyNjMwMTcwNywiZXhwIjoxNzI2NDc0NTA3fQ.MeCtTgTr5nhunEiRAiXKidvzgC4tUCCk5nCFqmEFxcU

{
    "flashsale_name": "Name flashsale",
    "flashsale_banner": "https://i.ytimg.com/vi/iZ9Ehu5ICHk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD5GxgbcdPsfxCjobx-Sb9LCL5cpg",
    "flashsale_start_date": 1234253634537,
    "flashsale_end_date": 1334253634537,
    "flashsale_discount_percent": 5
}

###

PATCH {{url_dev}}/66e568dd1f168a9ce3ba4682
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67
x-client-id: 66caedd4533d3eefd8d16cc2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwicGVybWl0Ijp7InBlcm1pdF9zaG9wIjpmYWxzZSwiX2lkIjoiNjZjYWVkZDQ1MzNkM2VlZmQ4ZDE2Y2M0IiwicGVybWl0X3VzZXIiOnRydWUsInBlcm1pdF9tb2RlcmF0b3IiOmZhbHNlLCJwZXJtaXRfYWRtaW4iOnRydWUsInBlcm1pdF9ndWVzdCI6dHJ1ZSwicGVybWl0X3VzZXJJZCI6IjY2Y2FlZGQ0NTMzZDNlZWZkOGQxNmNjMiIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjVUMDg6Mzk6NDguNDAyWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDktMTRUMDc6NDc6NTQuMjM3WiIsIl9fdiI6MH0sImlhdCI6MTcyNjMwMTcwNywiZXhwIjoxNzI2NDc0NTA3fQ.MeCtTgTr5nhunEiRAiXKidvzgC4tUCCk5nCFqmEFxcU

{
    "items": [
        {
            "itemId": "66e50512853f9a3cccfcbec5",
            "quantity": 10
        }
    ]
}
