@url_dev=http://localhost:8000/v1/api/product
@api_key=3ba73ff48c21cd92f1f7fc1ce55e125f0bd176323da76c8abdfed7a79aeb56f6
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU5MmZkM2E0ZDZiZGYyYjNkMGViZDciLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwicGVybWl0Ijp7Il9pZCI6IjY2ZTkyZmQzYTRkNmJkZjJiM2QwZWJkYSIsInBlcm1pdF91c2VyIjpmYWxzZSwicGVybWl0X21vZGVyYXRvciI6ZmFsc2UsInBlcm1pdF9hZG1pbiI6dHJ1ZSwicGVybWl0X2d1ZXN0Ijp0cnVlLCJwZXJtaXRfc2hvcCI6ZmFsc2UsInBlcm1pdF91c2VySWQiOiI2NmU5MmZkM2E0ZDZiZGYyYjNkMGViZDciLCJjcmVhdGVkQXQiOiIyMDI0LTA5LTE3VDA3OjI5OjIzLjU3NVoiLCJ1cGRhdGVkQXQiOiIyMDI0LTA5LTE3VDA3OjI5OjIzLjU3NVoiLCJfX3YiOjB9LCJpYXQiOjE3Mjc3OTcxOTUsImV4cCI6MTcyNzk2OTk5NX0.Y7972__jchJJ2CFNjxGL99sK3o4MYYazE2IIRORvTag

###
POST {{url_dev}}
Content-Type: application/json
x-api-key: 3ba73ff48c21cd92f1f7fc1ce55e125f0bd176323da76c8abdfed7a79aeb56f6
x-client-id: 66e926d98c2f81cf4c283c45
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU5MjZkOThjMmY4MWNmNGMyODNjNDUiLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwicGVybWl0Ijp7Il9pZCI6IjY2ZTkyNmQ5OGMyZjgxY2Y0YzI4M2M0OCIsInBlcm1pdF91c2VyIjpmYWxzZSwicGVybWl0X21vZGVyYXRvciI6ZmFsc2UsInBlcm1pdF9hZG1pbiI6dHJ1ZSwicGVybWl0X2d1ZXN0Ijp0cnVlLCJwZXJtaXRfc2hvcCI6ZmFsc2UsInBlcm1pdF91c2VySWQiOiI2NmU5MjZkOThjMmY4MWNmNGMyODNjNDUiLCJjcmVhdGVkQXQiOiIyMDI0LTA5LTE3VDA2OjUxOjA1LjkwMVoiLCJ1cGRhdGVkQXQiOiIyMDI0LTA5LTE3VDA2OjUxOjA1LjkwMVoiLCJfX3YiOjB9LCJpYXQiOjE3MjY1NTU5MTIsImV4cCI6MTcyNjcyODcxMn0.4wXQD0Z865RDboHSQ60rcmEuWAIKhwtmkOLS_hs6tSM


{
    "product_name": "test 005",
    "product_thumb": ["https://i.ytimg.com/vi/iZ9Ehu5ICHk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD5GxgbcdPsfxCjobx-Sb9LCL5cpg"],
    "product_description": "this is desc",
    "product_slogan": "this is slogan",
    "product_price": {
        "origin": 12,
        "sale": 10
    },
    "product_type": "book",
    "product_shop": "66caedd4533d3eefd8d16cc2",
    "product_attributes": {
        "author": "thhuian",
        "sheets": 123,
        "publishing_house": "Van hoc",
        "language": "vi"
    },
    "product_quantity": "1000"
}

###
PATCH {{url_dev}}/66e1531e6d1a1218bdfc6a10
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67
x-client-id: 66caedd4533d3eefd8d16cc2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwiaWF0IjoxNzI2MDM3NDM2LCJleHAiOjE3MjYyMTAyMzZ9.73H14TkoO4RL-6kUpgTDAthnVDrGCU2VvmXeIANvLgk

{
    "product_name": "test 002",
    "product_thumb": [{
        "url": "image.png",
        "public_id": "12bn324"
    }],
    "product_description": "this is desc",
    "product_slogan": "this is slogan",
    "product_price": {
        "sale": 9
    },
    "product_type": "book",
    "product_shop": "66caedd4533d3eefd8d16cc2",
    "product_attributes": {
        "author": "thhuian12"
    },
    "product_quantity": "1000"
}

###

GET {{url_dev}}
Content-Type: application/json
x-api-key: {{api_key}}

###

GET {{url_dev}}/flashsale/all
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67

###

GET {{url_dev}}/66e143f85a30edf447af3fd9
Content-Type: application/json
x-api-key: {{api_key}}

###

GET {{url_dev}}/draft/all
Content-Type: application/json
x-api-key: {{api_key}}
x-client-id: 66caedd4533d3eefd8d16cc2
authorization: {{token}}

###

GET {{url_dev}}/published/all
Content-Type: application/json
x-api-key: {{api_key}}
x-client-id: 66caedd4533d3eefd8d16cc2
authorization: {{token}}

###

PUT {{url_dev}}/published/66e143f85a30edf447af3fd9
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67
x-client-id: 66caedd4533d3eefd8d16cc2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwiaWF0IjoxNzI2MDM3NDM2LCJleHAiOjE3MjYyMTAyMzZ9.73H14TkoO4RL-6kUpgTDAthnVDrGCU2VvmXeIANvLgk

###

PUT {{url_dev}}/unpublished/66e143f85a30edf447af3fd9
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67
x-client-id: 66caedd4533d3eefd8d16cc2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwiaWF0IjoxNzI2MDM3NDM2LCJleHAiOjE3MjYyMTAyMzZ9.73H14TkoO4RL-6kUpgTDAthnVDrGCU2VvmXeIANvLgk

###

GET {{url_dev}}/search/test
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67

###

DELETE {{url_dev}}/66e50234baa44062610d5126/book
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67
x-client-id: 66caedd4533d3eefd8d16cc2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwiaWF0IjoxNzI2MjgzNTQ0LCJleHAiOjE3MjY0NTYzNDR9.M5-_v_VjjGq-hvOQm4VWn3pnb66IGP57wqfOMXCNLg0
