@url_dev=http://localhost:8000/v1/api
@api_key=3ba73ff48c21cd92f1f7fc1ce55e125f0bd176323da76c8abdfed7a79aeb56f6

POST {{url_dev}}/access/signup
Content-Type: application/json
x-api-key: 3ba73ff48c21cd92f1f7fc1ce55e125f0bd176323da76c8abdfed7a79aeb56f6

{
    "user_name": "hitim",
    "user_email": "hi.tim.gi.the@gmail.com",
    "user_password": "123456"
}

###

POST {{url_dev}}/access/login
Content-Type: application/json
x-api-key: {{api_key}}

{
    "user_email": "hi.tim.gi.the@gmail.com",
    "user_password": "123456"
}

###
POST {{url_dev}}/otp/verify-otp
Content-Type: application/json
x-api-key: 3ba73ff48c21cd92f1f7fc1ce55e125f0bd176323da76c8abdfed7a79aeb56f6

{
    "email": "hi.tim.gi.the@gmail.com",
    "otp": "559593"
}

###
POST {{url_dev}}/otp/send-otp-again
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67

{
    "email": "hi.tim.gi.the@gmail.com"
}

###
POST {{url_dev}}/otp/forgot-password
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67

{
    "email": "hi.tim.gi.the@gmail.com"
}

###
PUT {{url_dev}}/user/change-password
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67
x-client-id: 66caedd4533d3eefd8d16cc2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwiaWF0IjoxNzI1MjQ3MjU0LCJleHAiOjE3MjU0MjAwNTR9.-cusvTZdXmV8H_ae95S843kZCDKLR3Yzhzm5KztbmmA

{
    "password": "123456"
}

###
GET {{url_dev}}/user/refresh-token
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67
x-client-id: 66caedd4533d3eefd8d16cc2
refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwiaWF0IjoxNzI1MjQ3MTI4LCJleHAiOjE3MjU4NTE5Mjh9.Ct0YR0KbuAtTKgSiBumvmS8cageMLC6IlCz75PxLve4

###
PUT {{url_dev}}/user/avatar
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67
x-client-id: 66caedd4533d3eefd8d16cc2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwiaWF0IjoxNzI1MjQ3MjU0LCJleHAiOjE3MjU0MjAwNTR9.-cusvTZdXmV8H_ae95S843kZCDKLR3Yzhzm5KztbmmA

{
    "picture": "image01.png"
}

###
PUT {{url_dev}}/user
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67
x-client-id: 66caedd4533d3eefd8d16cc2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwiaWF0IjoxNzI2MjgzNTQ0LCJleHAiOjE3MjY0NTYzNDR9.M5-_v_VjjGq-hvOQm4VWn3pnb66IGP57wqfOMXCNLg0

{
    "user_account": "hi.tim",
    "user_address": "thanh hoa",
    "user_gender": "male"
}

###
GET {{url_dev}}/user/all?filter=permit_admin&sort=ctime
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67
x-client-id: 66caedd4533d3eefd8d16cc2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwicGVybWl0Ijp7InBlcm1pdF9zaG9wIjpmYWxzZSwiX2lkIjoiNjZjYWVkZDQ1MzNkM2VlZmQ4ZDE2Y2M0IiwicGVybWl0X3VzZXIiOnRydWUsInBlcm1pdF9tb2RlcmF0b3IiOmZhbHNlLCJwZXJtaXRfYWRtaW4iOmZhbHNlLCJwZXJtaXRfZ3Vlc3QiOnRydWUsInBlcm1pdF91c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJjcmVhdGVkQXQiOiIyMDI0LTA4LTI1VDA4OjM5OjQ4LjQwMloiLCJ1cGRhdGVkQXQiOiIyMDI0LTA4LTI1VDEyOjMwOjUyLjE0MloiLCJfX3YiOjB9LCJpYXQiOjE3MjYyOTUyMzQsImV4cCI6MTcyNjQ2ODAzNH0.tMPfdfToTiX36Ji4XDOBqj1A6H3joW0kHTudGKdNlI8

###
PUT {{url_dev}}/user/permission/66caedd4533d3eefd8d16cc2
Content-Type: application/json
x-api-key: 62deb3015e786cefbffa7cd33e488f5d262fc7754c9ce4aba884fb116ec08c67
x-client-id: 66caedd4533d3eefd8d16cc2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJlbWFpbCI6ImhpLnRpbS5naS50aGVAZ21haWwuY29tIiwicGVybWl0Ijp7InBlcm1pdF9zaG9wIjpmYWxzZSwiX2lkIjoiNjZjYWVkZDQ1MzNkM2VlZmQ4ZDE2Y2M0IiwicGVybWl0X3VzZXIiOnRydWUsInBlcm1pdF9tb2RlcmF0b3IiOmZhbHNlLCJwZXJtaXRfYWRtaW4iOmZhbHNlLCJwZXJtaXRfZ3Vlc3QiOnRydWUsInBlcm1pdF91c2VySWQiOiI2NmNhZWRkNDUzM2QzZWVmZDhkMTZjYzIiLCJjcmVhdGVkQXQiOiIyMDI0LTA4LTI1VDA4OjM5OjQ4LjQwMloiLCJ1cGRhdGVkQXQiOiIyMDI0LTA4LTI1VDEyOjMwOjUyLjE0MloiLCJfX3YiOjB9LCJpYXQiOjE3MjYyOTUyMzQsImV4cCI6MTcyNjQ2ODAzNH0.tMPfdfToTiX36Ji4XDOBqj1A6H3joW0kHTudGKdNlI8

{
    "permit_admin": true
}
